openapi: 3.0.3
info:
  description: Scrap fabric ledger into database. Needs administrative privileges.
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Hyperledger Cactus Plugin - Block Fabrick PErsistance
  version: 2.0.0-rc.1
servers:
- url: /
paths: {}
components:
  schemas: {}
