name: Optimised CI

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

jobs:
  magic-ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List the changed files
        run: |
          echo "List of files changed: ${{ steps.changed-files.outputs.all_changed_files }}"