name: Optimised CI

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

jobs:
  magic-ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: ","

      - name: Output the vars
        run: echo ${{ steps.changed-files.outputs.stdout }}