


---
name: PR - Commit Parity
'on':
  pull_request:
    branches:
      - main
      - dev
      - petermetz/**
  push:
    branches:
      - main
      - dev

jobs:
  pr-commit-parity:
    name: PR and Commit messages Parity
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Use Node.js v18.18.2
      uses: actions/setup-node@v4.0.2
      with:
        node-version: v18.18.2
    - name: Execute script
      id: execute-script
      run: |
         PR_COMMIT_PARITY_OUTPUT=$(node tools/pr-commit-parity.js ${{ github.event.pull_request.url }})
         echo "PR_COMMIT_PARITY_OUTPUT=$PR_COMMIT_PARITY_OUTPUT" >> "$GITHUB_OUTPUT"

    - name: List output
      run: echo "The output is ${{ steps.execute-script.outputs.PR_COMMIT_PARITY_OUTPUT }}"