name: ghpkg-all-java-api-clients-publish

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Indy SDK
      run: >
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
          && sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable" \
          && sudo apt-get update \
          && sudo apt-get install -y \
              libindy \
              libnullpay \
              libvcx \
              indy-cli \
          && sudo rm -f /etc/apt/sources.list.d/sovrin.list*

    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0

    - name: Get the latest release version
      run: |
        export GITVERSION=$(git describe --tags | awk -F'.' '{print $$1}')
        echo "GITVERSION=$GITVERSION" >> $GITHUB_ENV

    - uses: actions/setup-java@v3.11.0
      with:
        distribution: 'adopt'
        java-version: '8'
    
    - name: Setup maven for packaging jars
      uses: s4u/setup-maven-action@2.8.0

    - name: Set up NodeJS v16.9.1
      uses: actions/setup-node@v3.6.0
      with:
        node-version: v16.9.1

    - run: npm run configure

    - name: build-cactus-cmd-api-server-java-client
      run: |
        WDIR=`pwd`
        cd ${WDIR}/packages/cactus-cmd-api-server/src/main/java/generated/openapi/java-client
        mvn clean package

    - name: publish-cactus-cmd-api-server-java-client
      uses: actions/upload-artifact@v3.0.0
      with:
        name: cactus-cmd-api-server-java-client-${{ env.GITVERSION }}.jar
        path: packages/cactus-cmd-api-server/src/main/java/generated/openapi/java-client/target/openapi-java-client-1.jar