name: Build kotlin artifacts and publish to github packages

on:
  push:
    branches: [master, main, dev]

  pull_request:
    branches: [master, main, dev]

jobs:
  publish-cactus-cmd-api-server:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Indy SDK
      run: >
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
          && sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable" \
          && sudo apt-get update \
          && sudo apt-get install -y \
              libindy \
              libnullpay \
              libvcx \
              indy-cli \
          && sudo rm -f /etc/apt/sources.list.d/sovrin.list*

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get the latest release version
      run: |
        export GITVERSION=$(git describe --tags | awk -F'.' '{print $$1}')
        echo "GITVERSION=$GITVERSION" >> $GITHUB_ENV

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set up NodeJS v16.9.1
      uses: actions/setup-node@v2.1.2
      with:
        node-version: v16.9.1

    - run: yarn configure

    - name: Build the package
      run: |
        WDIR=`pwd`
        cd ${WDIR}/packages/cactus-cmd-api-server/src/main/kotlin/generated/openapi/kotlin-client
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: Upload the generated kotlin artifact to github packages
      uses: actions/upload-artifact@v3.0.0
      with:
        name: cactus-cmd-api-server-${{ env.GITVERSION }}.jar
        path: packages/cactus-cmd-api-server/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar

  publish-cactus-core-api:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Indy SDK
      run: >
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
          && sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable" \
          && sudo apt-get update \
          && sudo apt-get install -y \
              libindy \
              libnullpay \
              libvcx \
              indy-cli \
          && sudo rm -f /etc/apt/sources.list.d/sovrin.list*

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get the latest release version
      run: |
        export GITVERSION=$(git describe --tags | awk -F'.' '{print $$1}')
        echo "GITVERSION=$GITVERSION" >> $GITHUB_ENV

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set up NodeJS v16.9.1
      uses: actions/setup-node@v2.1.2
      with:
        node-version: v16.9.1

    - run: yarn configure

    - name: Build the package
      run: |
        WDIR=`pwd`
        cd ${WDIR}/packages/cactus-core-api/src/main/kotlin/generated/openapi/kotlin-client
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: Upload the generated kotlin artifact to github packages
      uses: actions/upload-artifact@v3.0.0
      with:
        name: cactus-core-api-${{ env.GITVERSION }}.jar
        path: packages/cactus-core-api/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar